services:
  server:
    build: src/server/.
    environment:
      - PORT=80
    networks:
      hey:
        ipv4_address: 192.168.1.2

  client:
    build: src/client/.
    environment:
      - HOSTNAME=192.168.1.2
      - PORT=80
    networks:
      hey:
        ipv4_address: 192.168.1.3
    depends_on:
      - server

networks:
  hey:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
